### ISSUE TITLE
How to read nested key?

### ISSUE THREAD

**Issue by pro100svitlo** [KJ002/read-yaml#55]
Hi!

Can you please help to specify how exactly I can read the nested value in my yaml file?

Thanks!

yaml example:
```yaml
environment:
  first: "value first"
  second: 'value second'
```

**Comment by pro100svitlo** [comment]
The answer is:
```yaml
        with:
          file: './my_yaml.yaml'
          key-path: '["environment", "first"]'
```
