### ISSUE TITLE
Bad indentation on code example in the README.md

### ISSUE THREAD

**Issue by lenowng** [KJ002/read-yaml#6]
Specifically on Line 33, corrected:
```yaml
on: [ push, pull_request ]

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './action.yml'          # File to read from
          key-path: '["runs", "using"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
```
